server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security
    username: web_user
    password: pass

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 604163455826-dr1sjh6e6j7bh0bg0cgt2tgrcf4ha2mi.apps.googleusercontent.com
            client-secret: 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
            scope: 
            - email
            - profile
            
          facebook: 
            client-id: 778180233844845
            client-secret: 31e77a5a8b1701f473b762971d8359eb
            scope: 
            - email
            - public_profile
            